### ISSUE TITLE
eslint errors 

### ISSUE THREAD

**Issue by karan717** [sam16222/CookBook#56]
Showing "Compiled with Problems" error when loading the application, possibly due to eslint error issues.
![WhatsApp Image 2022-10-07 at 12 47 24 PM](https://user-images.githubusercontent.com/41316333/194605681-6a78317b-c1b8-42f0-86e7-235df68e5032.jpeg)

**Comment by dearpriyankasa** [comment]
Have addressed the typescript issues and tried to resolve them

**Comment by dearpriyankasa** [comment]
The solution is available in  PR https://github.com/sam16222/CookBook/pull/53. Kindly review and merge to close the issue
